name: Using Cache

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"        
        type: boolean    
        default: true 

      node-version:
        description: "Node version"
        required: false
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x
        
       

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./caching/react-app
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: caching/react-app/node_modules
          key: cache-key-${{hashFiles( "caching/react-app/package-lock.json") }} 

      - if: ${{ ! steps.build.outputs.cache-hit == true }} 
        name: Install dependencies
        run:  npm ci

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
